version: '3'
services:
  db:
      container_name: db
      image: mysql:latest
      ports:
       - "3306:3306"  
      environment:
         - MYSQL_USER=me
         - MYSQL_ALLOW_EMPTY_PASSWORD=1
      volumes:
        # - /home/user/db/mysql/data:/var/lib/mysql
         - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
